aks:
  credentials:
    nexus:
      id: "nexus"
      type: "UsernamePasswordMultiBinding"
      varuser: "NEXUS_USERNAME"
      varpassword: "NEXUS_PASSWORD"
    project_token:
      id: "${project}-gitops-token-${deploymentEnvironment}"
      type: "UsernamePasswordMultiBinding"
      varuser: "PROJECT_GITOPS_USER"
      varpassword: "PROJECT_GITOPS_TOKEN"
    acr_build_sp:
      id: "${project}-az-sp"
      type: "StringBinding"
      varkey: "ACRBUILD_SP"
    acr_build_tenant:
      id: "${project}-tenant"
      type: "StringBinding"
      varkey: "ACRBUILD_TENANT"
    acr_build_secret:
      id: "${project}-secret"
      type: "StringBinding"
      varkey: "ACRBUILD_SECRET"
    acr_build_subscription:
      id: "${project}-subscription"
      type: "StringBinding"
      varkey: "ACRBUILD_SUBSCRIPTION"

eks:
  credentials:
    nexus:
      id: "nexus"
      type: "UsernamePasswordMultiBinding"
      varuser: "NEXUS_USERNAME"
      varpassword: "NEXUS_PASSWORD"
    project_token:
      id: "${project}-gitops-token-${deploymentEnvironment}"
      type: "UsernamePasswordMultiBinding"
      varuser: "PROJECT_GITOPS_USER"
      varpassword: "PROJECT_GITOPS_TOKEN"
    ecr_aws_region:
      id: "${project}-ecr-region"
      type: "StringBinding"
      varkey: "ECR_REGION"
    ecr_aws_access_key_id:
      id: "${project}-ecr-aws-access-key-id"
      type: "StringBinding"
      varkey: "ECR_AWS_ACCESS_KEY_ID"
    ecr_aws_secret_access_key:
      id: "${project}-ecr-aws-secret-access-key"
      type: "StringBinding"
      varkey: "ECR_AWS_SECRET_ACCESS_KEY"
